### ISSUE TITLE
error of ModelNet40 Classification

### ISSUE THREAD

**Issue by CodeWZT** [IRMVLab/Point-Mamba#12]
Hi, thank for the excellent work.
I try to run the modelnet40 classification task and prepare the environment. an error happend:
`Traceback (most recent call last):
  File "/opt/conda/envs/mamba/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 74, in _wrap
    fn(i, *args)
  File "/opt/conda/envs/mamba/lib/python3.10/site-packages/thsolver/solver.py", line 425, in worker
    the_solver.run()
  File "/opt/conda/envs/mamba/lib/python3.10/site-packages/thsolver/solver.py", line 400, in run
    eval('self.%s()' % self.FLAGS.SOLVER.run)
  File "<string>", line 1, in <module>
  File "/opt/conda/envs/mamba/lib/python3.10/site-packages/thsolver/solver.py", line 323, in train
    self.train_epoch(epoch)
  File "/opt/conda/envs/mamba/lib/python3.10/site-packages/thsolver/solver.py", line 159, in train_epoch
    output = self.train_step(batch)
  File "/opt/data/private/logic/Point-Mamba/classification.py", line 48, in train_step
    loss, accu = self.forward(batch)
  File "/opt/data/private/logic/Point-Mamba/classification.py", line 40, in forward
    logits = self.model(data, octree, octree.depth)
  File "/opt/conda/envs/mamba/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/envs/mamba/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/envs/mamba/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1519, in forward
    else self._run_ddp_forward(*inputs, **kwargs)
  File "/opt/conda/envs/mamba/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1355, in _run_ddp_forward
    return self.module(*inputs, **kwargs)  # type: ignore[index]
  File "/opt/conda/envs/mamba/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/envs/mamba/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/data/private/logic/Point-Mamba/models/PointMambacls.py", line 49, in forward
    features = self.backbone(data, octree, depth)
  File "/opt/conda/envs/mamba/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/envs/mamba/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/data/private/logic/Point-Mamba/models/PointMamba.py", line 299, in forward
    octree = OctreeT(octree, self.nempty,
  File "/opt/data/private/logic/Point-Mamba/models/PointMamba.py", line 57, in __init__
    self.build_t()
  File "/opt/data/private/logic/Point-Mamba/models/PointMamba.py", line 61, in build_t
    self.build_batch_idx(d)
  File "/opt/data/private/logic/Point-Mamba/models/PointMamba.py", line 65, in build_batch_idx
    self.batch_idx[depth] = self.patch_partition(batch, depth, self.batch_size)
  File "/opt/data/private/logic/Point-Mamba/models/PointMamba.py", line 69, in patch_partition
    tail = data.new_full((num,) + data.shape[1:], fill_value)
RuntimeError: Trying to create tensor with negative dimension -2147486448: [-2147486448]`
Have you encountered the same error before?

**Comment by Aristo23333** [comment]
> Hi, thank for the excellent work. I try to run the modelnet40 classification task and prepare the environment. an error happend: `Traceback (most recent call last): File "/opt/conda/envs/mamba/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 74, in _wrap fn(i, *args) File "/opt/conda/envs/mamba/lib/python3.10/site-packages/thsolver/solver.py", line 425, in worker the_solver.run() File "/opt/conda/envs/mamba/lib/python3.10/site-packages/thsolver/solver.py", line 400, in run eval('self.%s()' % self.FLAGS.SOLVER.run) File "<string>", line 1, in <module> File "/opt/conda/envs/mamba/lib/python3.10/site-packages/thsolver/solver.py", line 323, in train self.train_epoch(epoch) File "/opt/conda/envs/mamba/lib/python3.10/site-packages/thsolver/solver.py", line 159, in train_epoch output = self.train_step(batch) File "/opt/data/private/logic/Point-Mamba/classification.py", line 48, in train_step loss, accu = self.forward(batch) File "/opt/data/private/logic/Point-Mamba/classification.py", line 40, in forward logits = self.model(data, octree, octree.depth) File "/opt/conda/envs/mamba/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl return self._call_impl(*args, **kwargs) File "/opt/conda/envs/mamba/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl return forward_call(*args, **kwargs) File "/opt/conda/envs/mamba/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1519, in forward else self._run_ddp_forward(*inputs, **kwargs) File "/opt/conda/envs/mamba/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1355, in _run_ddp_forward return self.module(*inputs, **kwargs) # type: ignore[index] File "/opt/conda/envs/mamba/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl return self._call_impl(*args, **kwargs) File "/opt/conda/envs/mamba/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl return forward_call(*args, **kwargs) File "/opt/data/private/logic/Point-Mamba/models/PointMambacls.py", line 49, in forward features = self.backbone(data, octree, depth) File "/opt/conda/envs/mamba/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl return self._call_impl(*args, **kwargs) File "/opt/conda/envs/mamba/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl return forward_call(*args, **kwargs) File "/opt/data/private/logic/Point-Mamba/models/PointMamba.py", line 299, in forward octree = OctreeT(octree, self.nempty, File "/opt/data/private/logic/Point-Mamba/models/PointMamba.py", line 57, in __init__ self.build_t() File "/opt/data/private/logic/Point-Mamba/models/PointMamba.py", line 61, in build_t self.build_batch_idx(d) File "/opt/data/private/logic/Point-Mamba/models/PointMamba.py", line 65, in build_batch_idx self.batch_idx[depth] = self.patch_partition(batch, depth, self.batch_size) File "/opt/data/private/logic/Point-Mamba/models/PointMamba.py", line 69, in patch_partition tail = data.new_full((num,) + data.shape[1:], fill_value) RuntimeError: Trying to create tensor with negative dimension -2147486448: [-2147486448]` Have you encountered the same error before?

Hi！ Have you changed the depth of the octree?
![image](https://github.com/IRMVLab/Point-Mamba/assets/128909624/4167e98a-dd3c-451e-88e3-75a2b1945147)

**Comment by CodeWZT** [comment]
@Aristo23333 thanks for your reply. i do not change the depth of the octree.
![image](https://github.com/IRMVLab/Point-Mamba/assets/88307728/7331707f-212d-4047-a178-f59bc101d7d0)
here is my settings. i run the original code without change any settings.

**Comment by HerculesJL** [comment]
@CodeWZT May I ask how you solved this problem?

**Comment by CodeWZT** [comment]
not yet

**Comment by CodeWZT** [comment]
> @CodeWZT May I ask how you solved this problem?
not yet

**Comment by Aristo23333** [comment]
Hi! Maybe you can refer to this issue https://github.com/IRMVLab/Point-Mamba/issues/18
